name: Build and Test .NET App

on:
  push:
    branches:
      - main

env:
  DOTNET_VERSIONS: "3.1 7.0 6.0"

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ${{ env.DOTNET_VERSIONS }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release
      
    - name: Run tests
      run: dotnet test

